### ISSUE TITLE
API Platform

### ISSUE THREAD

**Issue by carlobeltrame** [carlobeltrame/ecamp3#10]
### Pros
- Symfony-based, seemingly maintained way more actively than Laminas API Tools, backed by a french software development company
- Specialized primarily on API projects, most common use cases have existing solutions
- Speaks many different API standards, including HAL, making it easier for other services to use the eCamp API
- Also doctrine-based, we can keep all our existing entity classes
- Instead of the relatively confusing and home-made `extract` / `HydrateInfo` config, uses another approach by decoupling the HAL protocol specifics from the model / DTO domain
- Can use DTOs, but don't have to
- Registration / login logic is pre-implemented
- Existing, pre-built, standards-conform, tried-and-tested systems for: PATCH operations even with nested properties, validation messages tied to fields, createdAt/updatedAt fields in the DB
- Different validations for create and patch, as well as validations for nested entities are natively possible and will be automatically documented
- IRIs (URIs / self links) are used instead of IDs in the API to specify relations
- Docker Setup and Helm Chart (for Kubernetes deployment) is pre-implemented (of course we still need to adapt this for ecamp)
- Things like [soft-delete](https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html), [cursor-based pagination](https://api-platform.com/docs/core/pagination/#cursor-based-pagination) and [live updates](https://api-platform.com/docs/core/mercure/) are available as pre-implemented installable /activatable bundles
- OpenAPI and other API documentation (Hydra) is built in
- PHP 8 support is built in
- There are Symfony IDE plugins for PHPStorm and VSCode

### Contras
- Another big refactoring (but with both short-term and long-term benefits)
- No slow rolling change possible, "big bang" necessary (but better now than after we've gone live)
- Some hal-json-vuex adaptations needed (`item` instead of `items`, sending the Accept header `application/hal+json` (optional), empty collection relations are omitted in responses by default, embedded collections work a little differently), most of which would make sense going forward anyways
- There are some [open issues](https://github.com/api-platform/core/search?q=hal&type=issues) about the HAL serializer. But judging by some PRs, we could contribute back fixes for most of these and they would be accepted within a reasonable timeframe.
- Authorization is preferably based on JWT tokens, not PHP session ids (but we intend to go the OAuth / OIDC way anyways in the future, and session cookies are still possible)
- I didn't find a built-in way to do Input Filters (StringTrim, StripTags), only this issue: https://github.com/api-platform/api-platform/issues/232. But I implemented a system (based on PHP 8 attributes, to make it similar in use to validations) using a [custom Denormalizer](https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-adding-extra-data), which is [mentioned](https://api-platform.com/docs/core/extending/) in the API platform documentation as the solution to "post-process objects created from the payload sent in the HTTP request body"
- ~~No support for templated links (?)~~ https://symfony-devs.slack.com/archives/C39FKU9AL/p1617006666306200
- I haven't looked into sending Mails, but should be easily possible since some of the best PHP mail packages come from Symfony
- Print jobs infrastructure realization yet unclear (but they have [documentation](https://api-platform.com/docs/core/messenger/) for adding side effects to endpoints such as sending messages to a queue, and currently we're trying to live without print jobs anyway)
- On the community Slack channel, not all feedback is positive (especially some comments about simple use cases being simple, but custom logic being harder to implement). But neither is the feedback on the Laminas API Tools Slack channel...
- We don't have any experience with API platform yet. But it is very well documented, and there are a lot more code examples online than for Laminas.

### To consider
- The current version is 2.6. Later this year, API platform 3.0 will be released, but it will be the same as 2.7, without backward-compatibility layer. So if we start using 2.6+ now and don't use deprecated stuff, the upgrade to 3.0 should be very easy.

**Comment by usu** [comment]
Should we shift this issue to the main repo for further discussion?
